### PR TITLE
Replacement of a matmul + use of merge

### PR DESCRIPTION
**Pull request by jvdp1**

### CODE REVIEW

**Comment by jvdp1** [comment]
As discussed, to be tested on different datasets

**Comment by milancurcic** [comment]
Some quick and dirty timing timings of `examples/dense_mnist`. This is on AMD Ryzen 5 5500U (lower end mobile CPU):

## GFortran 11

* fpm profile debug:
  - `main`: ~35 s
  - `jvdp1:optim`: ~20s
* fpm profile release, `-fno-frontend-optim`:
  - `main`: ~25 s
  -  `jvdp1:optim`: ~9s
* fpm profile release:
  - `main`: ~8 s, does not converge (bad result!)
  -  `jvdp1:optim`: ~6 s, converges (good result!)

## ifort classic 2021.10

* profile release:
  - `main`: ~8.2 s
  -  `jvdp1:optim`: ~5.3 s

The overall training speed up is very nice, but the best part is that this PR also fixes the erroneous behavior with GFortran in release mode which previously required `-fno-frontend-optimize`.

@jvdp1 is this PR still a draft or can we mark it as "Ready for review"?

**Comment by jvdp1** [comment]
Thank you @milancurcic for testing the changes. It is actually ready.

**Comment by milancurcic** [comment]
Excellent, I'll go ahead and merge it then. Thank you!

**Review by milancurcic — APPROVED** [review]

**Pull request merged**
