### PR TITLE
Deploy ford documentation to GitHub Pages

### PR DESCRIPTION
**Pull request by rouson**
If this pull request is accepted, then the GitHub Pages feature needs to be selected in the repository Settings to enable deployment.

### CODE REVIEW

**Comment by milancurcic** [comment]
Thanks, this is very welcome! I can see that on `push` it will be deployed to the gh-pages branch. What happens on `pull_request`? I'm a GitHub Actions n00b, bear with me.

**Comment by milancurcic** [comment]
Is the UML stuff up-to-date with the work from #71?

**Comment by rouson** [comment]
> Thanks, this is very welcome! I can see that on `push` it will be deployed to the gh-pages branch. What happens on `pull_request`? Will it just build it and report that it builds? I'm a GitHub Actions n00b, bear with me.

Good question.  Possibly we should have it deploy on pull request too.  I'll research this and update the PR or get back to you.

**Comment by milancurcic** [comment]
I don't think it should deploy on PR, at least not to the gh-pages branch.

**Comment by milancurcic** [comment]
@rouson I see that this PR brings in the UML stuff besides the CI/CD flow. Would you like to get it up to speed with v0.9.0 or should we exclude it from this PR? 

IMO the Ford deployment is good to go, so this could be merged today if UML is excluded. Up to you.

**Comment by rouson** [comment]
@milancurcic are you wanting the UML scripts removed or just not deployed to GitHub Pages?  If it's the latter, then I think this PR accomplishes that because only the `doc/html` subdirectory gets deployed.

**Comment by milancurcic** [comment]
I'd exclude the UML stuff here only because it's partially complete. FORD deployment seems like a separate feature. Why don't we merge just that and work on UML in a separate PR?

**Comment by milancurcic** [comment]
@rouson I'd like to complete and merge this PR without UML however I don't have write permissions to your fork. Do you mind adding these permissions for me?

**Pull request closed without merging**
