### PR TITLE
Replace PR #48: FORD commits only

### PR DESCRIPTION
**Pull request by rouson**
As requested in an [issue comment], this PR contains only commits related to adding FORD documentation.  The text below is mostly copied from the now-closed PR #48, which the current PR replaces.

-------
1. Add a top-level `doc-generator.md` FORD project file that produces HTML documentation inside `doc/html/` and includes the top-level `README.md` content in the landing page: `doc/html/index.html`.
2. Replaces `!` with `!!` in comments _only_ in the `nf_random_mod` just after the first line of the module and just after the first lines of the procedure interface bodies.  Doing so triggers for to include the corresponding comments in the generated documentation. 
3. Add the `doc/` subdirectory to the `.gitignore` file.

If this PR gets merged, then executing
```
cd neural-fortran
ford doc-generator.md
```
will produce an uncompressed version of [doc.tar.gz](https://github.com/modern-fortran/neural-fortran/files/8429802/doc.tar.gz).

If approved, this PR can be updated to apply similar changes to the rest of the files in `src/`:
- [x] mod_activation.f90

- [x] mod_mnist.f90
- [x] mod_parallel.f90
- [x] mod_layer.f90
- [x] mod_network.f90

[issue comment]: https://github.com/modern-fortran/neural-fortran/pull/48#issuecomment-1090307589

### CODE REVIEW

**Comment by rouson** [comment]
@milancurcic this PR is now ready to merge.  The documentation now contains lots of text from the comments in the code.  See [doc.tar.gz](https://github.com/modern-fortran/neural-fortran/files/8429802/doc.tar.gz).

**Review by milancurcic — APPROVED** [review]
Looks great, thanks! I renamed the FORD file to make it shorter and obvious what tool it belongs to and added a few notes to the README.

Please merge when ready (I think you have sufficient permissions to do that, let me know if not).

A note about expanding the docstrings in the code. I'm preparing a large refactor coming in a week or two which will allow a network to use arbitrary layers (need dense, conv2d, maxpool, input, and flatten layers), which will be a pretty much a complete re-write of the framework, so any additional docstrings at this time would not have a long life. But the new code will maintain the FORD-friendly !! comments, so our FORD config will work as is. Will discuss the re-design in a separate issue.

**Comment by rouson** [comment]
@milancurcic it appears that I don't have the privileges required to merge this PR.

**Comment by milancurcic** [comment]
OK, can you try now?

**Comment by rouson** [comment]
Yes, done.  Thanks!

**Pull request merged**
