### PR TITLE
Proposition of API for the method `network % evaluate`

### PR DESCRIPTION
**Pull request by jvdp1**
Related to #179

### CODE REVIEW

**Comment by milancurcic** [comment]
I added example use of this to examples/dense_mnist.f90.

One challenge I found is that if we use the multiple metrics variant, we can't mix and match functions defined in `nf_metrics` and those in `nf_loss` (e.g. `metrics=[mse(), corr()]` is not allowed because an array constructor must have all types the same).

I think there may be a workaround by first staging metrics as `class(metric_type), allocatable :: metrics(:)` but I couldn't quite figured it out.

Even if it can't be done, it's a minor limitation IMO.

I'll add some tests too.

**Comment by milancurcic** [comment]
@jvdp1 actually, my challenge I mentioned above extends to even passing multiple metrics of the same parent type. Can you show me one example of invoking `net % evaluate_batch_1d_metrics()`?

**Comment by milancurcic** [comment]
I think once we add one example of passing multiple metrics (say, in a test program), we can merge this PR.

**Comment by jvdp1** [comment]
> One challenge I found is that if we use the multiple metrics variant, we can't mix and match functions defined in `nf_metrics` and those in `nf_loss` (e.g. `metrics=[mse(), corr()]` is not allowed because an array constructor must have all types the same).

Indeed, you are right. The same problem happens also with multiple metrics of the same parent type. So, it seems that `evaluate_batch_1d_metrics` is not possible and should be removed.

**Comment by jvdp1** [comment]
A possible solution could be [this one ](https://gitlab.com/everythingfunctional/heterogeneous_list) proposed by Brad. But it sounds to me a bit too complex for what we want to achieve.

**Comment by milancurcic** [comment]
Thank you!

**Pull request merged**
